# Uncomment for use with GPU
# services:
#   reach_ros:
#     environment:
#       NVIDIA_DRIVER_CAPABILITIES: all
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]